### PR TITLE
Fix: Change the directory in which the command is run

### LINKED ISSUE #11: Terraform module is not recognized
I ran terraform init in GitHub Actions step, but the module is not recognized. This is probably because the directory to run tflint is not `working_directory`.

```
Error: `parameter_store` module is not found. Did you run `terraform init`?

  on dev/parameter_store.tf line 1, in module "parameter_store":
   1: module "parameter_store" {
```

- workflow/tflint.yaml

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: ["dev"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.24
          tf_actions_subcommand: init
          tf_actions_working_dir: ${{ matrix.workdir }}
          tf_actions_cli_credentials_token: ${{ secrets.TFC_TOKEN }}
      - name: Lint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ${{ matrix.workdir }}
          flags: >-
            --module
            --enable-rule=terraform_dash_in_output_name
            --enable-rule=terraform_dash_in_resource_name
            --enable-rule=terraform_dash_in_data_source_name
            --enable-rule=terraform_dash_in_module_name
```

### PR DESCRIPTION
**Pull request by yukin01**
Fix #11

### CODE REVIEW

**Comment by Vlaaaaaaad** [comment]
Huh, really curious how the tests in https://github.com/reviewdog/action-tflint/blob/master/.github/workflows/test.yml worked since they made use of the `working_directory` parameter. I'll retest manually and then likely merge this fix 🙂 

Also, please fix the `shellcheck` warning.

**Comment by yukin01** [comment]
Thanks for the review.
Both Terraform and TFlint, you need to run the command after you go to the working directory.

https://github.com/hashicorp/terraform-github-actions/blob/master/src/main.sh#L121
https://github.com/terraform-linters/tflint#does-tflint-check-modules-recursively

These would be helpful.

**Comment by Vlaaaaaaad** [comment]
Thank you so much for your contribution @yukin01! I forgot to say that 😞 

I'll review and test this later today or early tomorrow, and likely merge this PR!

**Comment by Vlaaaaaaad** [comment]
Hm... @yukin01 could you share an example this action fails on? 

I did some initial tests and it seems to be working just fine. I have no idea how it works without `cd`-ing into the folder, but it does.

The action is defined as:
```
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: "folder/deeper" # Change working directory
          reporter: github-pr-review # Change reporter
```
and I get the following output:
```
folder/deeper/example.tf:3:19: error: "t69.2xlarge" is an invalid value as instance_type ()
```

These are just some initial tests and it is late here so I am very likely missing something.

**Comment by yukin01** [comment]
@Vlaaaaaaad 
I've added a test that fails if you don't cd. It succeeds in this pull request, but fails in #13.
(Sorry, I ran CI so many times that another test got caught in the rate limit.)

**Comment by Vlaaaaaaad** [comment]
Aha! Thank you!

I'll look into this tomorrow 🤞

**Review by Vlaaaaaaad — APPROVED** [review]

**Comment by Vlaaaaaaad** [comment]
Yup, tested this and re-confirmed the issue. 

Thank you so much for your contribution @yukin01!

**Pull request merged**
