### PR TITLE
Fix tflint exit code in tests

### PR DESCRIPTION
**Pull request by sksat**
SSIA.

Ref:
- https://github.com/terraform-linters/tflint/pull/1191
- https://github.com/terraform-linters/tflint/blob/a8b001c820d3ac813b153c61f936419e1a45411c/docs/user-guide/config.md#force

### CODE REVIEW

**Comment by kstiehl** [comment]
The tests fail because tflint seems to return `3` instead of `2`

**Comment by sksat** [comment]
This change was introduced in tflint version 0.32.0, so update tflint version in test.

**Comment by sksat** [comment]
Additionally, it seems `Looking up the latest tflint version` on `macos-latest` is broken now.

https://github.com/reviewdog/action-tflint/runs/5272791137?check_suite_focus=true

**Review by haya14busa — APPROVED** [review]
Thanks! :+1:

**Comment by review-dog** [comment]
Hi, @sksat! We merged your PR to reviewdog! 🐶
Thank you for your contribution! ✨

**We just invited you to join the @reviewdog organization on GitHub.**
Accept the invite by visiting https://github.com/orgs/reviewdog/invitation.
By joining the team, you'll be a part of reviewdog community and can help the maintenance of reviewdog.

Thanks again!

**Pull request merged**
