### PR TITLE
Transform action as composite run steps

### LINKED ISSUE #23: Move the action to composite run steps
On August 7 2020, [GitHub announced composite run steps actions](https://github.blog/changelog/2020-08-07-github-actions-composite-run-steps/) which are basically "_run this shell script_"-based actions.

Converting this action to composite run steps would both simplify the code and lower the runtime of the action( and thus the costs).

Inspiration: https://github.com/reviewdog/action-golangci-lint/pull/46 + https://github.com/reviewdog/action-golangci-lint/pull/48

### PR DESCRIPTION
**Pull request by RomainBelorgey**
Fix https://github.com/reviewdog/action-tflint/issues/23

Looks to work fine when used.
Let me know if fine.

### CODE REVIEW

**Comment by Vlaaaaaaad** [comment]
Hey!

Awesome, thank you so much for working on this! Your contribution is appreciated! Looks like some tests also need updating.

I don't have the bandwidth to review this now, but I expect that I will have some time this weekend or sometime next week. Sorry 😞

**Comment by RomainBelorgey** [comment]
> Hey!
> 
> Awesome, thank you so much for working on this! Your contribution is appreciated! Looks like some tests also need updating.
> 
> I don't have the bandwidth to review this now, but I expect that I will have some time this weekend or sometime next week. Sorry disappointed

Nw, will check if I can update the tests.
Some are failing because of the dockerfile and other the `if` condition

**Comment by RomainBelorgey** [comment]
Wondering if the tests are failing because it is from a forked repository :thinking: : 
```
  reviewdog: This is Pull-Request from forked repository.
  GitHub token doesn't have write permission of Check API, so reviewdog will
  report results via logging command [1].
  [1]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
  reviewdog: Reporting results for "tflint"
  reviewdog: No results found for "tflint". 1 results found outside diff.
```

**Comment by Vlaaaaaaad** [comment]
Hm... could be 🤔 

I hoped I would have some time to look into your PR this weekend but I did not 😞 I'll try to fit this in before next Monday so we can get it merged! I am sorry I'm taking so long

**Comment by RomainBelorgey** [comment]
> Hm... could be thinking
> 
> I hoped I would have some time to look into your PR this weekend but I did not disappointed I'll try to fit this in before next Monday so we can get it merged! I am sorry I'm taking so long

Nw, take your time :+1:

**Comment by Vlaaaaaaad** [comment]
Hey @RomainBelorgey. Apologies, I am rather busy with some personal projects and I don't have any bandwidth to allocate for this right now 😞

My initial thoughts were that some weird `PATH` issues were at fault for the tests failing, but I did not have any time to test.

I hope I'll be able to get back to this by EOY, but no promises.

@reviewdog/actions-maintainer any of y'all can take a look at this?

**Comment by haya14busa** [comment]
I invited @RomainBelorgey to reviewdog org. You can create a pr from the same repo to test from non-forked repo.

This test is very suspicious and not good test if it always fails only for or from forked repo. I think we should fix it.

**Comment by RomainBelorgey** [comment]
> I invited @RomainBelorgey to reviewdog org. You can create a pr from the same repo to test from non-forked repo.
> 
> This test is very suspicious and not good test if it always fails only for or from forked repo. I think we should fix it.

Okay thanks, I will see to test that next week :+1:

**Pull request closed without merging**
