### PR TITLE
[GHES] Use GitHub URL from default env var

### LINKED ISSUE #37: GHES Native Support
It looks like part of this action is not properly detecting when the API URL is for GHES. Per the [Environment Variables](https://docs.github.com/en/enterprise-server@3.0/actions/reference/environment-variables#default-environment-variables) doc, `GITHUB_API_URL` is available to use.

```
 Running tflint with reviewdog 🐶 ...
  reviewdog: post failed for tflint: fail to parse diff: GET https://api.github.com/repos/myorg/myrepo/pulls/31: 401 Bad credentials []
Error: Process completed with exit code 1.

### PR DESCRIPTION
**Pull request by Vlaaaaaaad**
Fixes https://github.com/reviewdog/action-tflint/issues/37

By default, GitHub sets the URL to the GitHub Server in [`GITHUB_API_URL`](https://docs.github.com/en/enterprise-server@3.0/actions/reference/environment-variables#default-environment-variables). For the hosted "github.com" that most people use, that is `https://api.github.com`. For GitHub Enterprise Server it may be something like `https://api.github.company.com`.

Reviewdog expects the URL in  [`GITHUB_API`](https://github.com/reviewdog/reviewdog#reporter-github-pullrequest-review-comment--reportergithub-pr-review). This PR connects the two variables together. 

~Unsolved question: should we also add an extra option to set `REVIEWDOG_INSECURE_SKIP_VERIFY`?~

### CODE REVIEW

**Comment by Vlaaaaaaad** [comment]
Keeping this as a draft and I'll be waiting on feedback from @mcaulifn to see if it works. 


Concerns:
- we hardcode a `/` at the end of the URL because [`reviewdog` expects that. For the default GitHub Actions hosted workers we get reviewdog: `post failed for tflint: fail to parse diff: BaseURL must have a trailing slash, but "https://api.github.com" does not`](https://github.com/reviewdog/action-tflint/pull/38/checks?check_run_id=2630340629#step:3:25). I don't like this extra character and I feel that should be documented somewhere.
- `macos` runner fails for some reason?! I think it may be a transient GitHub issue, but we'll see.

**Comment by mcaulifn** [comment]
@Vlaaaaaaad Yes, this does work for self-hosted Linux runners with GHES.

**Comment by Vlaaaaaaad** [comment]
Woo, GitHub Actions is back to normal and all the checks passed!

I had 2 previous concerns, and both are fixed:
- adding a `/` at the end of the URL. I am no longer concerned about that as `reviewdog` is the one that expects the `/` and GitHub docs seem to indicate setting the URL without a trailing `/`
- also adding an option for setting `REVIEWDOG_INSECURE_SKIP_VERIFY`. I don't see a need right now. If somebody needs it we can add it as a follow-up PR

I am marking this as ready for review!

**Review by haya14busa — CHANGES_REQUESTED** [review]
We should check `GITHUB_API` from reviewdog binary instead of setting it from every actions.

Also, users should be able to set env vars outside actions (`GITHUB_ENV` environment file), so users can set env vars like `REVIEWDOG_INSECURE_SKIP_VERIFY` and `GITHUB_API_URL` i beleve.

**Comment by Vlaaaaaaad** [comment]
> We should check GITHUB_API from reviewdog binary instead of setting it from every actions.

Agreed, but that would take a while. Should I create an issue in [reviewdog/reviewdog](https://github.com/reviewdog/reviewdog/issues) to track that?

> Also, users should be able to set env vars outside actions (GITHUB_ENV environment file), so users can set env vars like REVIEWDOG_INSECURE_SKIP_VERIFY and GITHUB_API_URL i believe.

I agree that `REVIEWDOG_INSECURE_SKIP_VERIFY` should be manually set by the user using `GITHUB_ENV`, but I see no issue in this action setting `GITHUB_API_URL = GITHUB_API` until reviewdog checks that variable too. 
It's a better user experience, don't you think? We can remove that as soon as reviewdog adds support!

**Comment by Vlaaaaaaad** [comment]
@haya14busa do you think we can merge this as a temporary workaround until reviewdog checks `GITHUB_API` too?

**Comment by shogo82148** [comment]
fixed by https://github.com/reviewdog/action-tflint/pull/40

**Pull request closed without merging**
